# Generated by Django 4.0.5 on 2022-09-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0003_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='brk',
            field=models.BooleanField(default=False),
        ),
    ]
