# Generated by Django 4.0.5 on 2022-09-30 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0004_alter_shop_brk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
