# Generated by Django 4.0.5 on 2022-10-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0005_delete_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='')),
                ('brk', models.BooleanField(default=False)),
            ],
        ),
    ]
